# 服务器配置
server:
  # 服务器端口
  port: 80
# 服务器编码格式
spring:
  http:
    encoding:
      charset: utf-8
  thymeleaf:
  # 模板路径前缀
  # prefix: classpath:/templates/
  # 模板路径后缀
  # suffix: .html
  # 是否开启模板缓存（测试环境不开启）
    cache: false
  # 使用非严格解析的HTML5格式（需要添加NekoHTML库依赖）
  # mode: LEGACYHTML5

  # 静态资源配置
#  mvc:
#    static-path-pattern: /**
    # 不使用页面标签默认ICO图标
#    favicon:
#      enabled: true
#  resources:
#    static-locations: classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/resources/,classpath:/META-INF/resources/
  # 数据源配置
  datasource:
    # 驱动配置信息
    # 驱动类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动名
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/iab
    # 数据库用户登录名
    username: root
    # 数据库用户登录密码
    password: abc123

    # Druid连接池配置
    # 初始化连接数大小
    initialSize: 5
    # 最小连接数
    minIdle: 5
    # 最大连接数
    maxActive: 20
    # 获取连接等待超时时间（单位：毫秒）
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接（单位：毫秒）
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间（单位：毫秒）
    minEvictableIdleTimeMillis: 300000
    # 定义数据库查询测试语句
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    show-sql: true


# 控制台多彩输出
  output:
    ansi:
      enabled: detect

# Druid连接池监控信息配置
druid:
 # 监控模块登陆名
 loginUsername: admin
 # 监控模块登陆密码
 loginPassword: admin
 # 是否允许清空统计数据
 resetEnable: no
 # 白名单
 allow: null
 # 黑名单
 deny: null

# 全局Debug模式
#debug: false

# logback日志配置
logging:
#设置文件，可以是绝对路径，也可以是相对路径。
# file: /filelog.log
#设置目录，会在该目录下创建spring.log文件，并写入日志内容
 path: /logFile

# mybatis配置
mybatis:
  mapper-locations: classpath:MapperFile/*.xml
  type-aliases-package: loclhost.Model


